trigger:
  tags:
    include:
      - v*

pr: none

stages:
  - stage: 'build_and_deploy_to_cdn'
    displayName: 'BuildAndCopy'
    pool:
      vmImage: 'windows-latest'
    jobs:
      - job: 'Build'
        displayName: 'Build'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '19.x'
            displayName: 'install node'
          - script: |
              npm install && npm run build && ls dist
            displayName: 'Build'
          - publish: $(System.DefaultWorkingDirectory)/dist
            artifact: dist
      - deployment: deploy_dev
        displayName: deploy dev
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: dist
                - task: AzureFileCopy@5
                  inputs:
                    SourcePath: "$(Pipeline.Workspace)/dist"
                    azureSubscription: $(AzureSubscription_dev)
                    Destination: 'AzureBlob'
                    storage: $(StorageAccountName_dev)
                    ContainerName: '$web'
                    BlobPrefix: 'sdk'
      - deployment: deploy_uat
        displayName: deploy uat
        environment: uat
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: dist
                - task: AzureFileCopy@3
                  displayName: 'Copy to UAT'
                  inputs:
                    SourcePath: '$(System.DefaultWorkingDirectory)/dist'
                    azureSubscription: $(AzureSubscription_uat)
                    Destination: 'AzureBlob'
                    storage: $(StorageAccountName_uat)
                    ContainerName: '$web'
                    BlobPrefix: 'sdk'
      - deployment: deploy_prd
        displayName: deploy prd
        environment: prd
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: dist
                - task: AzureFileCopy@3
                  displayName: 'copy to prd'
                  inputs:
                    SourcePath: '$(System.DefaultWorkingDirectory)/dist'
                    azureSubscription: $(AzureSubscription_prd)
                    Destination: 'AzureBlob'
                    storage: $(StorageAccountName_prd)
                    ContainerName: '$web'
                    BlobPrefix: 'sdk'
