trigger:
  tags:
    include:
      - v*

pr: none

stages:
  - stage: 'build_and_deploy_to_cdn'
    displayName: 'BuildAndCopy'
    pool:
      vmImage: 'windows-latest'
    jobs:
      - job: 'Build'
        displayName: 'Build'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'install node'
          - script: |
              npm install && npm run build && ls dist
            displayName: 'Build'
          - task: AzureFileCopy@3
            displayName: 'Copy to Dev'
            inputs:
              SourcePath: '$(System.DefaultWorkingDirectory)/dist'
              azureSubscription: $(AzureSubscription_dev)
              Destination: 'AzureBlob'
              storage: $(StorageAccountName_dev)
              ContainerName: '$web'
              BlobPrefix: 'sdk'
          - task: AzureFileCopy@3
            displayName: 'Copy to UAT'
            inputs:
              SourcePath: '$(System.DefaultWorkingDirectory)/dist'
              azureSubscription: $(AzureSubscription_uat)
              Destination: 'AzureBlob'
              storage: $(StorageAccountName_uat)
              ContainerName: '$web'
              BlobPrefix: 'sdk'
          - task: AzureFileCopy@3
            displayName: 'copy to prd'
            inputs:
              SourcePath: '$(System.DefaultWorkingDirectory)/dist'
              azureSubscription: $(AzureSubscription)
              Destination: 'AzureBlob'
              storage: $(StorageAccountName)
              ContainerName: '$web'
              BlobPrefix: 'sdk'
