trigger:
  tags:
    include:
      - v*

pr: none

stages:
  - stage: 'build'
    displayName: 'build to dist'
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: 'Build'
        displayName: 'Build'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'install node'
          - script: |
              npm install && npm run build && ls dist
            displayName: 'Build'
          - publish: $(System.DefaultWorkingDirectory)/dist
            artifact: sdk
  - stage: 'dev'
    pool:
      vmImage: 'windows-latest'
    displayName: 'deploy to dev'
    dependsOn: 'build'
    jobs:
      - deployment: deploy_dev
        displayName: deploy dev
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: sdk
                - script: |
                    ls $(Pipeline.Workspace)\sdk
                - task: AzureFileCopy@5
                  inputs:
                    SourcePath: '$(Pipeline.Workspace)\\sdk'
                    azureSubscription: $(AzureSubscription_dev)
                    Destination: 'AzureBlob'
                    storage: $(StorageAccountName_dev)
                    ContainerName: '$web'
  - stage: 'uat'
    pool:
      vmImage: 'windows-latest'
    displayName: 'deploy to uat'
    dependsOn: 'build'
    jobs:
      - deployment: deploy_uat
        displayName: deploy uat
        environment: uat
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: sdk
                - task: AzureFileCopy@5
                  displayName: 'Copy to UAT'
                  inputs:
                    SourcePath: '$(Pipeline.Workspace)\\sdk'
                    azureSubscription: $(AzureSubscription_uat)
                    Destination: 'AzureBlob'
                    storage: $(StorageAccountName_uat)
                    ContainerName: '$web'
  - stage: 'prd'
    pool:
      vmImage: 'windows-latest'
    displayName: 'deploy to prd'
    dependsOn: 'build'
    jobs:
      - deployment: deploy_prd
        displayName: deploy prd
        environment: prd
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: sdk
                - task: AzureFileCopy@5
                  displayName: 'copy to prd'
                  inputs:
                    SourcePath: '$(Pipeline.Workspace)\\sdk'
                    azureSubscription: $(AzureSubscription_prd)
                    Destination: 'AzureBlob'
                    storage: $(StorageAccountName_prd)
                    ContainerName: '$web'
